plugins {
    id 'fml-loom' version '0.1'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'ModdedMITE'
        url = uri('https://maven.limingzxc.top/repository/maven-public/')
    }
}

configurations {
    fml
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    fml 'com.github.MinecraftIsTooEasy:FishModLoader:3.4.2'
    implementation 'com.github.MinecraftIsTooEasy:FishModLoader:3.4.2'

    implementation "com.github.MinecraftIsTooEasy:ManyLib:2.3.1"
    implementation "com.github.MinecraftIsTooEasy:ModMenu:10.1.1"
    implementation 'com.github.MinecraftIsTooEasy:RustedIronCore:1.5.5'

    implementation 'com.github.MinecraftIsTooEasy:YesSteveModel-MITE:1.0.1'

    localRuntime 'com.github.MinecraftIsTooEasy:GeckoLib-MITE:1.0.0'
    localRuntime 'com.github.MinecraftIsTooEasy:FastUtil:8.5.12'
    localRuntime 'com.fasterxml.jackson.core:jackson-databind:2.9.10.8'
    localRuntime 'org.joml:joml:1.10.8'
    localRuntime 'javax.vecmath:vecmath:1.5.2'
    localRuntime 'com.github.MinecraftIsTooEasy:Gson:2.10.1'
}

def fmlResolvedFile = configurations.fml.files.iterator().next()

loom {
    mergedMinecraftJar()

    mods {
        'Yes Steve Model: Model Expansion' {
            sourceSet sourceSets.main
        }
    }
}

loom.setFML(fmlResolvedFile)
dependencies.add('mappings', loom.fmlMCPMappings())

processResources {
    inputs.property 'version', project.version

    filesMatching('fml.mod.json') {
        expand 'version': project.version
    }
}

apply from: 'gradle/repository-models.gradle'

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.named('sourcesJar').configure {
    dependsOn(tasks.named('generateModelExpansionModels'))
    exclude('assets/ysmu_model_expansion/**')
    exclude('META-INF/YSMU_MODEL_EXPANSION.md')
}

tasks.named('runClient', JavaExec).configure { exec ->
    def user = project.hasProperty('username') ? project.username : 'Dev'
    exec.setArgs(['--username', user, '--session', '0', '--width', '854', '--height', '480'])
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.maven_group
            artifactId = project.archives_base_name
            version = project.mod_version
            from components.java
        }
    }
}
