# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fish Properties
minecraft_version=1.6.4-MITE
yarn_mappings=1.6.4
loader_version=0.15.0

# Mod Properties
mod_version=1.0.1
mod_id=ysmu_model_expansion
mod_name=Yes Steve Model: Model Expansion
archives_base_name=ysmu-model-expansion

# Maven Properties
maven_group=org.moddedmite
maven_id=ysmu-model-expansion

# Run Properties
username=Alex
screen_width=854
screen_height=480
